### ISSUE TITLE
Struktur aplikasi 

### ISSUE THREAD

**Issue by reyhan240501** [reyhan240501/program_matematika#1]
Mohon segera dikerjakan

**Comment by aripdev** [comment]
siap mas ketu @reyhan240501  pokok.e josss

**Comment by reyhan240501** [comment]
joosss

**Comment by aripdev** [comment]
Mas @reyhan240501  ini bro sudah selesai [https://github.com/reyhan240501/program_matematika/commit/a9bf0534987db0be6a0a1a9e7ccf5ff25ec554eb](url)

**Comment by aripdev** [comment]
mantag gak mas bro

**Comment by reyhan240501** [comment]
mantapbzzzz

**Comment by aripdev** [comment]
yang lain goib @SGWN @munifsoleh0805 @rendisaputra1258
